name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Cache Hugging Face datasets
      uses: actions/cache@v4
      with:
        path: ~/.cache/huggingface
        key: ${{ runner.os }}-huggingface-${{ hashFiles('**/lockfiles') }}
        restore-keys: |
          ${{ runner.os }}-huggingface-

    - name: Install dependencies
      run: |
        pip install -e . --extra-index-url https://download.pytorch.org/whl/cu121
        pip install black

    - name: Check code formatting with black
      run: |
        black --check .

    - name: Run unittests
      run: |
        python -m unittest discover -s src -p "*_test.py"
